### ISSUE TITLE
RFC:User Switching

### ISSUE THREAD

**Issue by treverthomasET** [opencabstandard/opencab#25]
## Summary
We've identified a need to support multi-user logins to allow for driver switching to be reflected in the HOS Consumer application when querying `HOSContract.METHOD_GET_HOS` and detect a change in `KEY_HOS`.

When a single app is acting as both Identity provider and HOS provider, the active driver can be unambiguously signaled to consuming apps via the isDriving property available as part of the Identity contract.

However, there is currently no way for an HOS consumer to determine which driver is active (in a legal and ELD sense) in the case where the ELD app is providing HOS information but chooses to consume Identity information, for example, as part of an single sign-on setup. This is relevant in cases where a third party app C is providing Identity information to a workflow app A and an ELD app B, as well as the case where workflow app A consumes HOS from ELD app B, and app B consumes Identity from app A.

To support this the Consumer App (Eleos) will need to know the Active Driver's `username` when the Active Driver changes. This `username` must match the provided `IdentityContract.DriverSession.username` during the IdentityConsumers(ELD app) query `METHOD_GET_LOGIN_CREDENTIALS`.

### Data
Add `username` within the HOSContract.HOSData structure
```
{
  "clocks": [],
  "logoutAction": "",
  "manageAction": "",
  "username":""
}
```
Unfortunately, this change would require a new version of `HOSStatus` as [discussed in this commit](https://github.com/opencabstandard/opencab/commit/8f802cef4061e78986c1e40c1aa110d56f4bdd49) because `Parcel` does not play nicely with newly added variables unrecognized by the system receiving the `Parcel`

This leaves us with two options:
1) Create an HOSStatusV3 that extends Parcel and is behind a new `HOSContract.version` and send/receive this data via `Bundle.putParcel/Bundle.getParcel`
2) Create an HOSData/ClockData/TeamHOSData purely as a data object and send/receive this data via `Bundle.putString/Bundle.getString` where each is converted to JSON before passing along to the HOS Consumer

Option 1 provides consistency with upgrade versions/naming however any future changes to this structure will require new Class names and versions along with additional work to continually support/check previous versions and use the designated class file.

Option 2 provides us a single version of HOSData/HOSClock/HOSTeamData that can be upgraded in the future without having to create a new named Class and should make backwards compatibility easier on Consumer/Providers alike. 

For long term support and less friction for both Consumer/Provider we would prefer to go with Option 2 and we have provided a [pull request](https://github.com/opencabstandard/opencab/pull/24) to show the work around these changes.

### Sample Provider Bundle call
From the provided Java object
```
//Build the HOSData object 
HOSData hosData = createHosData();
result.putString(HOSContract.KEY_HOS, gson.toJson(hosData));
```
Or straight from JSON itself
```
String jsonData = getHOSJson() //Provider generated
result.putString(HOSContract.KEY_HOS, jsonData);
```

### Sample Consumer Bundle call
```
HOSContract.HOSData hosData = gson.fromJson(result.getString(HOSContract.KEY_HOS), HOSContract.HOSData.class);
```

**Comment by pnc** [comment]
@ZonarTimH @Mehantp As Trever notes, this is a logical point to abandon `Parcel` and switch to JSON for these values so that it's easier to maintain backwards compatibility going forward (since JSON will ignore properties it doesn't recognize as opposed to crashing like Parcel does.)

I recognize this increases the relative effort for y'all to adopt this version (when/if you have a product desire to do so; our intention is to continue to support 0.3-style provider responses in our production apps.) Is it worth it to you?

**Comment by BoKlassen** [comment]
@pnc @treverthomasET We prefer option 2 with continued parcel support for v0.3. Although it will require a bit more maintenance on our end, we hope this will prevent any incompatibilities between our app's version and any HosConsumer app version. So we'll respond with an `HosStatusV2` Parcel only when the request targets v0.3, and respond with the JSON described in #24 for v0.4+ requests. Does this work for you?

**Comment by treverthomasET** [comment]
@BoKlassen That works for us. Appreciate the feedback!

**Comment by Jargle** [comment]
Hello, I after a change in structure, I am taking over point of contact from @ZonarTimH as Tim is in a different role within Zonar. I'm essentially the new Tim- I've been at Zonar for 7 years and am a former Android Developer here. I can provide a direct contact email address via DM as proof if required.

I prefer the JSON bundle via `putString` as it is more futureproof. `Parcelable` and `Serializable` objects are to be avoided and allow for no user-level error handling, crashing in the SDK at the first sign of compatibility.

I would not necessarily recommend Gson, though it is essentially an industry standard. If you wanted to compact the size of the library, I would instead recommend https://github.com/square/moshi as we've found it only adds 500Kb of weight to an application or library.

**Comment by treverthomasET** [comment]
@Jargle Hello there! 
It sounds like we are all in agreement that Option 2 (JSON route) is the path forward. I will then close this RFC and merge my open PR on Monday the 18th of December. 

>  I would instead recommend https://github.com/square/moshi

The reference for `Gson` is really just an example in case anyone is coming here for their first implementation of the HOSContract. Providers/Consumers can use their choice of JSON library as long as the data being sent matches the contract. Sorry for the confusion!

**Comment by BoKlassen** [comment]
@treverthomasET I was testing our OpenCab v0.4 integration with the `com.eleostech.qa` app, version 1.55 (20103) and feel the expectation is not 100% clear here.

This is the structure I understood from your previous comment, which is not working. The outer object is a Java Parcel and the `KEY_HOS` and `KEY_TEAM_HOS` keys each contain stringified versions of the JSON within.
```
{
    KEY_HOS: {
        "hosData": {
            // HosStatusV2 for driver
            "clocks": ClockData[],
            "logoutAction": "",
            "manageAction": "",
            "username":""
        }
    },
    KEY_TEAM_HOS: {
        "teamHosData": [
            // ... HosStatusV2 for each coDriver
        ]
    }
}
```

After some trial and error, I found that the same structure works when the `hosData` and `teamHosData` intermediate objects are removed. The `KEY_HOS` and `KEY_TEAM_HOS` values are still stringified versions of the JSON values within
```
{
    KEY_HOS: {
        // HosStatusV2 for driver
        "clocks": ClockData[],
        "logoutAction": "",
        "manageAction": "",
        "username":""
    },
    KEY_TEAM_HOS: [
        // ... HosStatusV2 for each coDriver
    ]
}
```

I'm guessing this is the correct structure you were trying to communicate since the PR's code seems to agree. Can you confirm that this is the correct format for v0.4?

**Comment by treverthomasET** [comment]
@BoKlassen Ah yes you are correct. That appears to have been a slip on my part and I apologize. My only correction to what you've listed above is:
```
{
    KEY_HOS: {
        // HOSData for driver
        "clocks": ClockData[],
        "logoutAction": "",
        "manageAction": "",
        "username":""
    },
    KEY_TEAM_HOS: {
        // ... List of HOSData for each coDriver
       "teamHosData": []
    }
}
```
Just to clarify to use the new `HOSData` and `HOSTeamData` for their corresponding keys.

**Comment by treverthomasET** [comment]
@BoKlassen I edited my above statement as it seems there was confusion on the `Team HOS Data` object. When I responded I left out that the `KEY_TEAM_HOS` does need the intermediate object `teamHosData` otherwise it won't properly capture when deserializing.

**Comment by BoKlassen** [comment]
For future readers, here is the format that worked
```
{
    KEY_HOS: {
        // HOSData for driver
        "clocks": ClockData[],
        "logoutAction": "",
        "manageAction": "",
        "username":""
    },
    KEY_TEAM_HOS: {
       "teamHosData": [] // List of HOSData for each coDriver
    }
}
```
Note that `KEY_TEAM_HOS` is an **object** and `teamHosData` is the only array.

CC @treverthomasET

**Comment by treverthomasET** [comment]
@BoKlassen Sorry for the miscommunication there and for any extra work you had to do on your end to track down this issue. Reaching out to see if there's anything else you've ran into along the way? Or if you had any questions?

**Comment by BoKlassen** [comment]
> @BoKlassen Sorry for the miscommunication there and for any extra work you had to do on your end to track down this issue. Reaching out to see if there's anything else you've ran into along the way? Or if you had any questions?

The 0.4 transition was smooth after this hiccup. Thanks for checking in.
